name = "sdc40_sandbox"
description = "sdc40_sandbox"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded"]

project-files = ["../gnat/fk723m1_zgt6.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_armv7m_systick_clock_timer = "*"
a0b_base = "*"
a0b_i2c = "*"
a0b_scd40 = "*"
a0b_stm32h723 = "*"
a0b_time = "*"
a0b_timer = "*"
light_fk723m1_zgt6 = "~0.2.0"
